apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stans
  namespace: stans
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stans.example.com
      secretName: stans-tls
  rules:
    - host: stans.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stans
                port:
                  name: http
